[tox]
envlist = py{310,313}, py{310,313}-lint

[testenv]
usedevelop = True
extras = dev
commands =
    pytest tests/

[testenv:py{310,313}-lint]
commands =
    python -m black --check --diff cofmupy
    python -m pylint cofmupy
deps =
    black==25.12.0
